# Generated by Django 5.2.1 on 2025-05-28 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_admitdate_patientdischargedetails_admit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='admit_date',
            new_name='admitDate',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.patient'),
        ),
    ]
