# Generated by Django 5.2.1 on 2025-05-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_rename_admit_date_patientdischargedetails_admitdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='admitDate',
            new_name='admit_date',
        ),
    ]
